- name: configure react instance
  hosts: _ansible_react
  become: true
  tasks:
    - name: upgrade all packages
      ansible.builtin.dnf: 
        name: '*'
        state: latest
    # we may need to uninstall any existing docker files from the centos repo first. 
    - name: remove Older versions of Docker if installed
      ansible.builtin.dnf:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
          - podman
          - runc
        state: removed

  # yum-utils is a collection of tools and programs for managing yum repositories, installing debug packages, source packages, extended information from repositories and administration.
    - name: Install "dnf-plugins-core"
      ansible.builtin.dnf:
        name: "dnf-plugins-core"
        state: latest

  # set up the repository (`yum_repository` modul can be used.)
    - name: Add Docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/rhel/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      ansible.builtin.package:
        name: docker-ce
        state: latest

    - name: Install Python and pip dependencies
      ansible.builtin.dnf:
        name: 
          - python3
          - python3-pip
          - python3-devel
          - gcc
        state: present

    - name: Upgrade pip to latest version
      ansible.builtin.pip:
        name: pip
        state: latest
        executable: pip3

    - name: Remove system-installed requests package
      ansible.builtin.dnf:
        name: python3-requests
        state: absent


    - name: Install Docker SDK for Python with compatible versions
      ansible.builtin.pip:
        name: 
          - docker==6.1.3
          - requests==2.31.0
          - urllib3<2.0
        state: present
        executable: pip3

    - name: Add user ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Reset ssh connection to pick up docker group
      ansible.builtin.meta: reset_connection

    - name: Wait for Docker daemon to be ready
      ansible.builtin.wait_for:
        path: /var/run/docker.sock
        state: present
        delay: 5
        timeout: 30

    - name: Test Docker connection
      ansible.builtin.command: docker version
      register: docker_version
      changed_when: false

    - name: Show Docker version
      ansible.builtin.debug:
        var: docker_version.stdout_lines

  # at this point do not forget change REACT_APP_BASE_URL env variable for nodejs node

    - name: copy files to the react node
      copy:
        src: /home/ec2-user/ansible/ansible-project/react/
        dest: /home/ec2-user/react

    - name: remove cw_react container
      community.docker.docker_container:
        name: o_react
        state: absent
        force_kill: true

    - name: remove clarusway/react image
      community.docker.docker_image:
        name: ondia/react
        state: absent
  
    - name: build container image
      community.docker.docker_image:
        name: ondia/react
        build:
          path: /home/ec2-user/react
        source: build
        state: present

    - name: Launch postgresql docker container
      community.docker.docker_container:
        name: o_react
        image: ondia/react
        state: started
        ports: 
        - "3000:3000"
      register: container_info
    
    - name: print the container info
      ansible.builtin.debug:
        var: container_info